### ISSUE TITLE
Incluir mi blog

### ISSUE THREAD

**Issue by abr4xas** [picodotdev/blog-stack#5]
**Nombre de la bitácora (requerido)**: El blog de abr4xas
**URL del bitácora (requerido)**: http://blog.abr4xas.org
**URL de la fuente («feed») a agregar (requerido)**: http://feeds.feedburner.com/ElBlogDeAbr4xas
**Dirección de correo electrónico (requerido)**: me@abr4xas.org
**Identificador de AdSense (data-ad-client) (opcional)**: ca-pub-7127443823639155
**Identificadores de bloques de anuncio AdSense (data-ad-slot) (opcional)**: 9038513565
**Identificador de Disqus (opcional)**: elblogdeabr4xas

**Comment by picodotdev** [comment]
Hola,

Tengo el placer de anunciarte que ya está agregada tu bitácora a Blog Stack asi que ¡bienvenido!. A partir de ahora todos los artículos que publiques serán agregados a BS.

Continua escribiendo contenido interesante en tu bitácora, trataré de seguir el contenido que publiques y revisaré el que has publicado ;).

Aquí tienes el último artículo que has publicado en BS:
http://www.blogstack.info/post/elblogdeabr4xas/2015/03/lamp-stack-para-usar-con-vagrant/

Un saludo,
